[package]
name = "derive_harbor"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
regex = "1.11.1"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
