[package]
name = "rusty_harbor"
version = "0.1.0"
edition = "2024"

[dependencies]
query_url.workspace = true
derive_builder = "0.20.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_urlencoded = "0.7.1"
serde_json = "1.0.142"